### ISSUE TITLE
Game Board

### ISSUE THREAD

**Issue by mikeapolis** [mikeapolis/briochewithdeath#4]
## Summary

As Betty Brioche, I need a board to place my sammiches for game. It should function the same as the familiar game Battleship, but less militaristic. Like the game battleship, I should be able to set square state and then interrogate them for that state.

## Acceptance Criteria

* The board is 10 x 10 - Horizontally A-J, vertically 1-10.
* The board is available for importing.
* The board is immutable (the board cannot be modified from external code).
* Each square in the board (e.g. B-3) can be set.
* Each square in the board can be queried for state (e.g. something exists there).
* The board has a locked state - once locked the board can't be "set" further.
* Each instance of a board can be associated with a player.

## Notes

* Methods will likely need to be refactored to take sammiches later.

**Comment by mollyocr** [comment]
All acceptance criteria met!
